#include "LIB/STD_TYPES.h"
#include "LIB/BIT_MATH.h"
#include "util/delay.h"
#include "DIO_INTERFACE.h"



void Stepper_VoidHalfStepCW(void)
{
	SET_BIT(PORTC , COIL_BLUE);
	CLR_BIT(PORTC , COIL_PINK);
	CLR_BIT(PORTC , COIL_YELLOW);
	CLR_BIT(PORTC , COIL_ORANGE);
	_delay_ms(3);
	
	SET_BIT(PORTC , COIL_BLUE);
	SET_BIT(PORTC , COIL_PINK);
	CLR_BIT(PORTC , COIL_YELLOW);
	CLR_BIT(PORTC , COIL_ORANGE);
	_delay_ms(3);
	
	CLR_BIT(PORTC , COIL_BLUE);
	SET_BIT(PORTC , COIL_PINK);
	CLR_BIT(PORTC , COIL_YELLOW);
	CLR_BIT(PORTC , COIL_ORANGE);
	_delay_ms(3);


	CLR_BIT(PORTC , COIL_BLUE);
	SET_BIT(PORTC , COIL_PINK);
	SET_BIT(PORTC , COIL_YELLOW);
	CLR_BIT(PORTC , COIL_ORANGE);
	_delay_ms(3);	


	CLR_BIT(PORTC , COIL_BLUE);
	CLR_BIT(PORTC , COIL_PINK);
	SET_BIT(PORTC , COIL_YELLOW);
	CLR_BIT(PORTC , COIL_ORANGE);
	_delay_ms(3);	

	CLR_BIT(PORTC , COIL_BLUE);
	CLR_BIT(PORTC , COIL_PINK);
	SET_BIT(PORTC , COIL_YELLOW);
	SET_BIT(PORTC , COIL_ORANGE);
	_delay_ms(3);	


	CLR_BIT(PORTC , COIL_BLUE);
	CLR_BIT(PORTC , COIL_PINK);
	CLR_BIT(PORTC , COIL_YELLOW);
	SET_BIT(PORTC , COIL_ORANGE);
	_delay_ms(3);	}

	SET_BIT(PORTC , COIL_BLUE);
	CLR_BIT(PORTC , COIL_PINK);
	CLR_BIT(PORTC , COIL_YELLOW);
	SET_BIT(PORTC , COIL_ORANGE);
	_delay_ms(3);	
	
}

void Stepper_VoidHalfStepACW(void)
{
	CLR_BIT(PORTC , COIL_BLUE);
	CLR_BIT(PORTC , COIL_PINK);
	CLR_BIT(PORTC , COIL_YELLOW);
	SET_BIT(PORTC , COIL_ORANGE);
	_delay_ms(3);
	
	CLR_BIT(PORTC , COIL_BLUE);
	CLR_BIT(PORTC , COIL_PINK);
	SET_BIT(PORTC , COIL_YELLOW);
	SET_BIT(PORTC , COIL_ORANGE);
	_delay_ms(3);
	
	CLR_BIT(PORTC , COIL_BLUE);
	CLR_BIT(PORTC , COIL_PINK);
	SET_BIT(PORTC , COIL_YELLOW);
	CLR_BIT(PORTC , COIL_ORANGE);
	_delay_ms(3);


	CLR_BIT(PORTC , COIL_BLUE);
	SET_BIT(PORTC , COIL_PINK);
	SET_BIT(PORTC , COIL_YELLOW);
	CLR_BIT(PORTC , COIL_ORANGE);
	_delay_ms(3);	


	CLR_BIT(PORTC , COIL_BLUE);
	SET_BIT(PORTC , COIL_PINK);
	CLR_BIT(PORTC , COIL_YELLOW);
	CLR_BIT(PORTC , COIL_ORANGE);
	_delay_ms(3);	

	SET_BIT(PORTC , COIL_BLUE);
	SET_BIT(PORTC , COIL_PINK);
	CLR_BIT(PORTC , COIL_YELLOW);
	CLR_BIT(PORTC , COIL_ORANGE);
	_delay_ms(3);	


	SET_BIT(PORTC , COIL_BLUE);
	CLR_BIT(PORTC , COIL_PINK);
	CLR_BIT(PORTC , COIL_YELLOW);
	CLR_BIT(PORTC , COIL_ORANGE);
	_delay_ms(3);	}

	SET_BIT(PORTC , COIL_BLUE);
	CLR_BIT(PORTC , COIL_PINK);
	CLR_BIT(PORTC , COIL_YELLOW);
	SET_BIT(PORTC , COIL_ORANGE);
	_delay_ms(3);	
}

void Stepper_VoidFullStepCW(void);
void Stepper_VoidFullStepCW(void);